name: Vercel Tests

on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'

jobs:
  build:
    name: Vercel Integration Tests
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Log deployment URL
        run: |
          echo "Running tests against deployment URL: ${{ github.event.client_payload.url }}"

      - name: Run tests
        run: bun test
        env:
          BASE_URL: ${{ github.event.client_payload.url }}
